[package]
name = "lintrunner"
version = "0.1.0"
authors = ["Michael Suo <suo@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "*"
anyhow = "*"
glob = "*"
tempfile = "*"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
termcolor = "1.1.2"
atty = "*"
textwrap = {version = "0.14", features = ["terminal_size"]}
similar = {version = "2.1.0", features = ["inline"]}
console = "*"
toml = "0.5.8"
log = "0.4.0"
env_logger = "0.9.0"
