name: 'Verify and Upload Alerts'
description: 'Verifies and Uploads a set of alerts to AWS'
inputs:
  alerts:
    description: 'JSON string to which represents alerts. It must conform to the alerting schema [put link here]'
    required: true
  organization:
    description: 'GitHub organization alerts are for'
    required: true
  repo:
    description: 'GitHub repository alerts are for'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Checkout pytorch/test-infra repository
      uses: actions/checkout@v3
      with:
        repository: pytorch/test-infra
        path: _test-infra
        ref: '11b4c6ee72c5c9b1829a20b4b903c5fe9a6aab09'
    - name: Check file
      shell: bash
      run: |
        cat _test-infra/tools/scripts/upload_alerts_to_aws.py
    - name: Run Script to Validate Alerts
      shell: bash
      run: | 
        python _test-infra/tools/scripts/validate_alerts.py --alerts '${{ inputs.alerts }}'

    - name: Run Script to Upload Alerts
      shell: bash
      run: |
       python _test-infra/tools/scripts/upload_alerts_to_aws.py --alerts '${{ inputs.alerts }}' --org "${{ inputs.organization }}" --repo "${{ inputs.repo }}"

    - name: Cleanup
      run: |
        rm -rf _test-infra
      shell: bash