name: 'Verify and Upload Alerts'
description: 'Verifies and Uploads a set of alerts to AWS'
inputs:
  alerts:
    description: 'JSON string to which represents alerts. It must conform to the alerting schema [put link here]'
    required: true
  organization:
    description: 'GitHub organization alerts are for'
    required: true
  repo:
    description: 'GitHub repository alerts are for'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Checkout pytorch/test-infra repository
      uses: actions/checkout@v3
      with:
        repository: pytorch/test-infra
        path: _test-infra
        ref: 'e18db87fd8d6b546d0a9f23795594f4df59245c2'
    - name: Check file
      shell: bash
      run: |
        cat _test-infra/tools/scripts/upload_alerts_to_aws.py
    - name: Run Script to Validate Alerts
      shell: bash
      run: | 
        python _test-infra/tools/scripts/validate_alerts.py --alerts '${{ inputs.alerts }}'

    - name: Run Script to Upload Alerts
      shell: bash
      # if: github.event_name != 'pull_request'
      run: |
       python _test-infra/tools/scripts/upload_alerts_to_aws.py --alerts '${{ inputs.alerts }}' --org "${{ inputs.organization }}" --repo "${{ inputs.repo }}" --dry-run [[ "${{ github.event_name }}" == "pull_request" ]]

    - name: Cleanup
      run: |
        rm -rf _test-infra
      shell: bash