[[linter]]
name = 'flake8'
patterns = ['**/*.py']
args = [
    'python3',
    'src/flake8_linter.py',
    '--binary=flake8',
    '--',
    '@{{PATHSFILE}}'
]

[[linter]]
name = 'rustfmt'
patterns = ['**/*.rs']
args = [
    'python3',
    'src/rustfmt_linter.py',
    '--binary=rustfmt',
    '--config-path=rustfmt.toml',
    '--',
    '@{{PATHSFILE}}'
]
