name: Test and deploy clickhouse-replicator-s3 lambda

on:
  push:
    branches:
      - main
      - csl/dynamo_clickhouse
    paths:
      - .github/workflows/clickhouse-replicator-lambda-s3.yml
      - aws/lambda/clickhouse-replicator-s3/**

defaults:
  run:
    working-directory: aws/lambda/clickhouse-replicator-s3

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: pip
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/test_gha_workflow_clickhouse_replicator_lambda
          aws-region: us-east-1
      - run: make deploy
