name: Scale GCP Cluster

on:
  schedule:
    # TODO every 5 minutes
    - cron: "SOMETHING HERE"
  workflow_dispatch:

jobs:
  autoscale-gcp:
    uses: ./.github/workflows/linux_job.yml
    with:
      repository: fairinternal/pytorch-gha-infra
      ref: main
      job-name: GCP Autoscaler 
      secrets-env: "GOOGLE_APPLICATION_CREDENTIALS ROCKSET_API_KEY"
      script: |
        # We would need to pass the creds file because the GCPClient authorizes
        # using that JSON. We would separately need to get the private key file
        # in-place so that we can do the SSH.
        conda create --yes --quiet -n gcp_env python=3.10
        conda activate gcp_env
        pip install -r requirements.txt
        cd gcp-scaler
        python3 scale.py \
          --workers-per-node=1 \
          --job-type=autoscale \
          --gce-project-name=pytorch-ossea13315f \
