on:
  workflow_dispatch: {}

name: Create Release Tag

jobs:
  tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    container: node:14
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y%m%d-%H%M%S')" >> "${GITHUB_OUTPUT}"

      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.date.outputs.date }}

  call-release:
    needs: tag
    uses: ./.github/workflows/lambda-do-release-runners.yml
    with:
      tag: v${{ needs.tag.outputs.date }}
