name: Lint

on:
  pull_request:
    paths:
      - mypy.ini
      - '**.py'
      - '**requirements.txt'
  push:
    branches:
      - main
    paths:
      - mypy.ini
      - '**.py'
      - '**requirements.txt'

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install --requirement=.mypy_requirements.txt
      - name: Run mypy
        env:
          MYPY_FORCE_COLOR: 1
        run: |
          mypy

  test-tools:
    name: Test tools
    if: ${{ github.repository == 'pytorch/test-infra' }}
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      docker-image: python:3.11.0-slim-bullseye
      runner: linux.large
      script: |
        ls -la 
        pwd
        
        # Environment setup
        echo ::group::setup Python environment
        python -m venv .venv/
        source .venv/bin/activate
        pip install pip==23.0.1 pytest==7.2.0 rockset==1.0.3
        echo ::endgroup::
        
        # Test tools
        python3 -m unittest discover -vs tools/tests -p 'test_*.py'
        
