name: log-classifier-lambda

on:
  pull_request:
    paths:
      - .github/workflows/log-classifier-lambda.yml
      - aws/lambda/log-classifier/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/log-classifier-lambda.yml
      - aws/lambda/log-classifier/**

defaults:
  run:
    working-directory: aws/lambda/log-classifier/

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo test

  deploy:
    needs: test
    # NB: We need to run the deployment process on the same OS that the lambda
    # is using, meaning AmazonLinux family, not GitHub ubuntu runner, to avoid
    # libc linking issue
    runs-on: linux.2xlarge
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_log-classifier-lambda
          aws-region: us-east-1
      - run: sudo yum install cargo
      - run: pip3 install cargo-lambda
      - run: cargo lambda build --release
      - run: cargo lambda deploy
