name: Scale Config Validator

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/scale_config_validation.yml
      - .github/scale-config.yml

jobs:
  scale-config-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests yaml

      - name: Validate Scale Config
        run: |
          ls
          echo "---updir"
          ls .github
          echo
          echo "PWD"
          pwd
          ls -l /home/runner/work/test-infra/test-infra/.github/scale-config.yml
          python3 .github/scripts/validate_scale_config.py