name: Test TorchFix

on:
  pull_request:
    paths:
      - .github/workflows/test-torchfix.yml
      - tools/torchfix/**
  workflow_dispatch:

jobs:
  test-torchfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r tools/torchfix/requirements-dev.txt
      - name: Run pytest
        run: |
          cd tools/torchfix
          pytest tests
      - name: Run flake8
        run: |
          cd tools/torchfix
          flake8
