name: Test mobile workflow

on:
  pull_request:
    paths:
      - .github/workflows/mobile_job.yml
      - .github/workflows/test_mobile_job.yml
      - tools/device-farm-runner/**
  workflow_dispatch:


jobs:
  test-mobile-job:
    uses: ./.github/workflows/mobile_job.yml
    with:
      device-type: ios
      runner: macos-latest
      project-arn: 'arn:aws:devicefarm:us-west-2:308535385114:project:b531574a-fb82-40ae-b687-8f0b81341ae0'
      ios-ipa-archive: 'https://ossci-assets.s3.amazonaws.com/TestApp.ipa'
      ios-xctest-zip: 'https://ossci-assets.s3.amazonaws.com/TestAppTests.xctest.zip'
