name: Update queue times dataset

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: torchci
jobs:
  update-queue-rockset:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn node scripts/updateQueueTimes.mjs
        env:
          OUR_AWS_ACCESS_KEY_ID: ${{ steps.aws_creds.outputs.aws-access-key-id }}
          OUR_AWS_SECRET_ACCESS_KEY: ${{ steps.aws_creds.outputs.aws-secret-access-key }}
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
