name: Update CI Wait Time Metric
on:
#  schedule:
    # Update the indices every 30 minutes
#    - cron: "*/30 * * * *"
  # Enable triggering this job manually using the API as well 
  push:
    branches:
      - 'zainr/kpi-ci-wait'
  workflow_dispatch:

jobs:
  update-kpi:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'pytorch/test-infra' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: x64
          check-latest: false
          cache: pip
          cache-dependency-path: |
            **/.ci/docker/requirements-ci.txt
            **/.github/requirements-gha-cache.txt

      - name: Install Python Packages
        run: |
          pip3 install rockset==1.0.3
          pip3 install boto3==1.19.12
          pip3 install pandas==1.5

      - name: Compute kpi and upload to RDS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
        run: |
          python3 .github/scripts/compute_and_upload_ci_wait_time_metric.py
